# -*- coding: utf-8 -*-
"""2SUM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rP8rqgIP_qsg0F0-_EkJmJOAPsvUujIL

# 알고리즘 - 2Sum
"""

'''
Input: nums = [2,7,11,15], target = 9
Output: [0,1]
Output: Because nums[0] + nums[1] == 9, we return [0, 1].
'''

nums = [2, 7, 11, 15]
target = 9

answer_list = []

for a in nums:
    nums2 = [a]
    for b in [x for x in nums if x not in nums2]:
        if a + b == target:
            answer_list.append(a)
            answer_list.append(b)
            nums.remove(a)
            nums.remove(b)

answer_list

class Solution(object):
    def twoSum(self, nums, target):
        for a in range(0, len(nums)):
            for b in range(a + 1, len(nums)):
                if nums[a] + nums[b] == target:
                    return [a+1, b+1]

        return -1

Solution.twoSum(1, [8, 2, 4, -2, -8], 0)