# -*- coding: utf-8 -*-
"""Degree Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n5ch_NWYvnYHkO83IvJelEQwHAW_Wzta
"""

# 각 요소의 개수를 세면 그 요소의 연결 수를 찾을 수 있다.

def Clear_data_list(a):
    return [list(map(int, (data.replace("\n", '')).split(" "))) for data in a]

def Flatten(data):
    output = []
    for item in data:
        if type(item) == list:
            output += Flatten(item)
        else:
            output += [item]
    return output

f = open('/content/drive/MyDrive/workspace/rosalind_deg.txt', 'r')
summary = f.readline().replace('\n', "").split(' ')
component = int(summary[0])
data = f.readlines()
f.close()

clear_list = Clear_data_list(data)
flatten_list = Flatten(clear_list)
answer_list = []

for a in range(1, component + 1):
    answer_list.append(flatten_list.count(int(a)))

g = open('/content/drive/MyDrive/workspace/answer.txt', 'w')
for b in answer_list:
    g.write(str(b))
    g.write(" ")
g.close()

def Clear_data_list(a):
    return [list(map(int, (data.replace("\n", '')).split(" "))) for data in a]

Clear_data_list(data)

lista = []
num = 6

for a in range(0, num):
    lista.append(#count수)